### PR TITLE
fix: Cuda crashes while open URL

### PR DESCRIPTION
**Pull request by veksha**
fixes https://github.com/Alexey-T/CudaText/issues/4519

@Alexey-T  @kvichans

### CODE REVIEW

**Comment by Alexey-T** [comment]
2 places of `urllib.parse.quote(ref, safe='/:#?=')` ? pls make a var.

**Comment by veksha** [comment]
@Alexey-T check

**Comment by Alexey-T** [comment]
ok.

**Comment by Alexey-T** [comment]
@veksha , can you add there this new func and use it?

```python
def safe_open_url(url):
    '''
    On Windows 10, app crashes when webbrowser.open* is called with running LSP server.
    '''
    if os.name=='nt':
        import subprocess
        subprocess.Popen(['start', url], shell=True)
    else:
        import webbrowser
        webbrowser.open_new_tab(url)
```

**Comment by veksha** [comment]
added new func call. looks OK? @Alexey-T

**Comment by Alexey-T** [comment]
no, I mean - include copy of "safe_open_url" to your patch. Plugin must work on old Cud too!

**Comment by veksha** [comment]
included

**Comment by Alexey-T** [comment]
okay.

**Comment by kvichans** [comment]
Thanks

**Comment by veksha** [comment]
Hi @kvichans,

We need to replace `['start', url]` with `['start', '', url]`
see new issue: https://github.com/Alexey-T/CudaText/issues/4533

**Pull request merged**
